default_language_version:
  python: python3.11.7

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: double-quote-string-fixer

- repo: https://github.com/asottile/pyupgrade
  rev: v2.38.2
  hooks:
  - id: pyupgrade
    args: ['--keep-percent-format', '--py311-plus']

- repo: https://github.com/myint/autoflake
  rev: v1.6.1
  hooks:
  - id: autoflake
    args: ['--in-place', '--remove-all-unused-imports']
    exclude: ^(data|\w+/migrations)/

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    exclude: ^(data|\w+/migrations)/

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.3.0
  hooks:
  - id: add-trailing-comma
    exclude: ^(data|\w+/migrations)/

- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: ^(data|\w+/migrations)/

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.981
  hooks:
  - id: mypy
    exclude: ^(data|\w+/migrations)/
    additional_dependencies: ['types-requests']
