version: '3.8'

services:
  web:
    build: backend/
    ports:
      - "8001:8001"
    depends_on:
      - redis


  celery:
    build: backend/
    command: poetry run celery -A backend.celery worker -l info
    depends_on:
      - web
      - redis

  redis:
    image: "redis:alpine"

  flower:
    build: backend/
    command: poetry run celery -A backend flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
